### ISSUE TITLE
Implement a MongoDB Backend to store data of URLs

### ISSUE THREAD

**Issue by christopher-koch** [christopher-koch/capstone-project#15]
## Value Proposition

**The user** ... (User, Author, logged in User...)  
**should be able to store/save his shortened urls** ... (describe the goal)  
**so that he can come back at any point and reuse/edit/delete/see the urls **
​

## Description

All current Data stored in the state "shortUrls" should be stored in a remote database
​

## Acceptance Criteria

- [ ] The data of "shortUrls" is stored in a remote Mongo Database
- [ ] The data isn't stored anymore in the localstorage of the user
      ​

## Tasks

- [ ] create a remote MongoDB and create some dummy-objects with dummy-entries
- [ ] connect the databse through an API with the APP
- [ ] Fetch the Data of the Database and import it into the App
- [ ] Create a Request/Response feature, so that the submitted URLs will be stored in the database
      ​

## Complexity

L

**Comment by TuncAlt** [comment]
Looks good, overall. Maybe next time you'll write from the user's point of view
