### ISSUE TITLE
Consistent and accessible UI / UX

### ISSUE THREAD

**Issue by christopher-koch** [christopher-koch/capstone-project#16]
## Value Proposition

**The user**
**should see a consistent, user friendly and accessible UI** ... (describe the goal)  
**so that he understands how to navigate the App without thinking or inaccessibility** ... (describe the reason)  
​

## Description

The app should look modern, be accessible for every visitor and don't make the user think how certain features are supposed to work.
​

## Acceptance Criteria

- [ ] consistent and easily accessible color scheme
- [ ] accessible and easy to read font and font-sizes
- [ ] accessible icons which speak for themselves
      ​

## Tasks

- [ ] implement an accessible color-scheme
- [ ] Mix styled components with global styling
- [ ] implement custom font and icons
      ​

## Complexity

L

**Comment by TuncAlt** [comment]
Looks good, overall. Maybe next time you'll write from the user's point of view
