### ISSUE TITLE
Redirect Shortlinks with API

### ISSUE THREAD

**Issue by christopher-koch** [christopher-koch/capstone-project#20]
## Value Proposition

**The user** ... (User, Author, logged in User...)  
**should be redirected to the long Url of the corresponding short url by using an API request/response** ... (describe the goal)  
**so that the performance will be improved** ... (describe the reason)  
​

## Description

Currently, the redirects are done by using a dynamic page and a router, which isn't optimal. This has to change and be done by an API request/response handler.
​

## Acceptance Criteria

- [ ] Redirect the user with an API request
- [ ] Other Features of Nextjs like middleware, nextResponse / nextResponse or other can be used.
      ​

## Tasks

- [ ] write some sort of  "handler" that redirects the user to the corresponding Long Url of the short URL.
      ​

## Complexity

L

**Comment by Tim-K93** [comment]
Good idea! Can´t wait for the outcome
