### ISSUE TITLE
Implement LocalstorageState for client-side rendering

### ISSUE THREAD

**Issue by christopher-koch** [christopher-koch/capstone-project#27]
**The user **  
**should see his changes through CRUD actions displayed immediately**  
**so that he doesn't has to experience loading times and has a better overall user experience**
​

## Description

Mirror Data from database in state-variable to improve client-side rendering.
​

## Acceptance Criteria

- [ ] loading-times for crud-actions are improved significantly

      ​

## Tasks

- [ ] Data gets mirrored from DB into state-variable
- [ ] data of state-variable is used to display data in the client, instead of the DB
- [ ] Change also get synced with the DB, so that it's always up-to-date
      ​

## Complexity

... M
