### ISSUE TITLE
Login-Bereich mit Next-Auth

### ISSUE THREAD

**Issue by christopher-koch** [christopher-koch/capstone-project#29]
## Value Proposition

**As a user**
**I want to login**
**so that i can see my shortened links, which are exclusive to me**
​

## Description

Add a login-feature so that a user can login and see his shortened links.
​

## Acceptance Criteria

- [ ] User can login via Github or Google Account
- [ ] User only sees his shortened links in the dashboard
      ​

## Tasks

- [ ] Implement Next Auth for user-authentification and login
- [ ] Save shortened Entries per user in db
      ​

## Complexity

L
