### ISSUE TITLE
Make website responsive for every screensize - (noch ausfüllen)

### ISSUE THREAD

**Issue by christopher-koch** [christopher-koch/capstone-project#30]
**The user**  
**should view the App on every Screen-size (mobile, tablet and desktop)**   
**so that he can use the app on every device**  
​

## Description

Make the App responsive for every screens-size.
​

## Acceptance Criteria

- [ ] The App design is fluid and responsive for every screen-size
- [ ] The UI changes accordingly to the screen-size
      ​

## Tasks

- [ ] Create a responsive Navigation
- [ ] Adapt sizes of fonts, icons, images etc.
- [ ] Change grid-layouts (mobile 1 column, tablet 2-3, desktop 3+)
      ​

## Complexity

L
