### ISSUE TITLE
Show Loading-Indicator when deleting or editing an entry

### ISSUE THREAD

**Issue by christopher-koch** [christopher-koch/capstone-project#32]
**As a user**
**I want to see a loading indicator when deleting or editing an item**
**so that i know it's being processed**
​

## Description

The user should see a loading indicator when deleting or editing an entry​

## Acceptance Criteria

- [ ] The icon of the delete/editing button changes when loading
      ​

## Tasks

- [ ] set a state when fetching
- [ ] change icon when fetch is loading
- [ ] change icon back to original icon and state to false
      ​

## Complexity

S

**Comment by Marcel-FR** [comment]
LGTM!
