### ISSUE TITLE
Implement real domain

### ISSUE THREAD

**Issue by christopher-koch** [christopher-koch/capstone-project#34]
**The user** 
**should be able to visit the app via a short, real domain** 
**so that his shortened links are actually short and not use the long preview url**
​

## Description

Make the App run on 5zu.de
​

## Acceptance Criteria

- [ ] App should be available on 5zu.de
- [ ] shortened links should look like "5zu.de/shortURL"
      ​

## Tasks

- [ ] Define official domain in project
- [ ] set it up in Vercel
      ​

## Complexity

S
